### ISSUE TITLE
Fix needed polyline functions

### ISSUE THREAD

**Issue by boryana-ilieva** [SeBecker/dc-egm#1]
We want to revisit the translated poly line functions as to ensure that they can handle inputs generated in previous steps and that results are the same as in the MatLab code.

- [ ] fix chop: example changes in retirement_model notebook.
- [ ] fix sort: explore if one can simply use np.sort or any other function already available in Python, else fix in whatever other way
- [ ] fix diff:  explore if one can use np.setdiff1d or any other function already available in Python, else fix in whatever other way

**Comment by SeBecker** [comment]
I replaced the sort function with the sort method from numpy. Additionally I reorganized the diff and chop function. They should work as intended from now on.
